# Generated by Django 4.2.8 on 2023-12-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalbase',
            name='age',
        ),
        migrations.AlterField(
            model_name='mentalbase',
            name='lastname',
            field=models.TextField(max_length=15, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='mentalbase',
            name='surname',
            field=models.TextField(max_length=15, verbose_name='Prénom'),
        ),
    ]
