# Generated by Django 4.2.8 on 2023-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_mentalbase_age_alter_mentalbase_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalbase',
            name='birthdate',
            field=models.DateField(auto_now=True, verbose_name='Date de naissance'),
        ),
    ]
