# Generated by Django 4.2.8 on 2023-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_mentalbase_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalbase',
            name='birthdate',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
    ]
